# The list of rules can be found here : https://github.com/realm/SwiftLint/blob/master/Rules.md

disabled_rules:
- discouraged_optional_boolean
- explicit_enum_raw_value
- identifier_name # Waiting for https://github.com/realm/SwiftLint/issues/2329 to be implemented to enable this rule
- nesting
- private_action
- trailing_whitespace
- type_name # Waiting for https://github.com/realm/SwiftLint/issues/2329 to be implemented to enable this rule
- void_return

opt_in_rules:
- anyobject_protocol
- closure_body_length
- closure_end_indentation
- closure_spacing
- collection_alignment
- contains_over_filter_count
- contains_over_filter_is_empty
- contains_over_first_not_nil
- contains_over_range_nil_comparison
- control_statement
- convenience_type
- discouraged_optional_boolean
- empty_collection_literal
- empty_count
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure
- empty_string
- empty_xctest_method
- explicit_enum_raw_value
- explicit_init
- fatal_error_message
- file_name
- first_where
- force_unwrapping
- identical_operands
- implicit_return
- large_tuple
- last_where
- legacy_multiple
- legacy_random
- literal_expression_end_indentation
- lower_acl_than_parent
- modifier_order
- multiline_arguments
- multiline_function_chains
- multiline_parameters
- number_separator
- operator_usage_whitespace
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
- private_action
- prohibited_super_call
- reduce_boolean
- reduce_into
- redundant_discardable_let
- redundant_nil_coalescing
- single_test_class
- sorted_first_last
- sorted_imports
- static_operator
- syntactic_sugar
- todo
- toggle_bool
- trailing_newline
- unneeded_parentheses_in_closure_argument
- untyped_error_in_catch
- unused_import
- unused_private_declaration
- vertical_parameter_alignment_on_call
- vertical_whitespace_closing_braces
- xct_specific_matcher
- yoda_condition

excluded:
- Pods
- Carthage
- Apollo/Sources/Modules/BackendModel/Sources/DTO/*

anyobject_protocol:
  severity: error

closure_spacing:
  severity: error

collection_alignment:
  severity: error

colon:
  severity: error

comma:
  severity: error

duplicate_imports:
  severity: error
                                                  
empty_enum_arguments:
  severity: error

explicit_init:
  severity: error

file_length:
  warning: 500
  error: 800

file_name:
  severity: warning
  excluded:
    - ClosureAliases

identifier_name:
  excluded:
    - x
    - y
    - "*Expectation" # This is not working at the moment but might in the future if SwiftLint implements it (https://github.com/realm/SwiftLint/issues/2329)

implicit_getter:
  severity: error

implicit_return:
  severity: error

large_tuple:
  warning: 3
  error: 5

line_length:
  warning: 160

lower_acl_than_parent:
  severity: error

modifier_order:
  severity: error

mark:
  severity: error

multiline_arguments:
  severity: error

multiline_function_chains:
  severity: error

opening_brace:
  severity: error

operator_usage_whitespace:
  severity: error

overridden_super_call:
  severity: error

override_in_extension:
  severity: error

pattern_matching_keywords:
  severity: error

reduce_boolean:
  severity: error

redundant_discardable_let:
  severity: error

single_test_class:
  severity: error

sorted_first_last:
  severity: error

superfluous_disable_command:
  severity: error

toggle_bool:
  severity: error
                                                  
trailing_newline:
  severity: error

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded:
    - "*Tests" # This is not working at the moment but might in the future if SwiftLint implements it (https://github.com/realm/SwiftLint/issues/2329)

unneeded_parentheses_in_closure_argument:
  severity: error

unused_closure_parameter:
  severity: error

unused_import:
  severity: error

unused_optional_binding:
  severity: error

unused_setter_value:
  severity: error

vertical_parameter_alignment:
  severity: error

vertical_parameter_alignment_on_call:
  severity: error

vertical_whitespace_closing_braces:
  severity: error

vertical_whitespace:
  severity: error

xct_specific_matcher:
  severity: error
